
project_id = "otvgheqffehoykaerckl"

[functions.get-referral-stats]
verify_jwt = true

[functions.send-referral-email]
verify_jwt = true

[functions.verify-referral]
verify_jwt = false

[functions.check-referral-limit]
verify_jwt = true
