
# A string that describes your project
name = 'AIDoctorNotes'

# The port and hostname to serve from
[serve]
  port = 54321
  hostname = 'localhost'

# The URL of your deployed project
# Used to generate URLs to your tables
api_url = 'https://your-project-url.supabase.co'

[api]
  # The URL of your custom API from the project dashboard
  # This defaults to your API_URL if not set
  url = 'https://your-project-url.supabase.co'
  
  # The anon key from your project dashboard
  anon_key = 'your-anon-key'
  
  # The service_role key from your project dashboard
  service_role_key = 'your-service-role-key'

[functions]
  # The path to your functions directory
  path = 'functions'
  
  [functions.analyze-image]
    verify_jwt = true
    
  [functions.anonymize-note]
    verify_jwt = true
    
  [functions.check-feature-access]
    verify_jwt = true
    
  [functions.check-referral-limit]
    verify_jwt = true
    
  [functions.cleanup-expired-data]
    verify_jwt = true
    
  [functions.contact-form]
    verify_jwt = false
    
  [functions.create-checkout]
    verify_jwt = true
    
  [functions.generate-soap]
    verify_jwt = true
    
  [functions.generate-soap-deepseek]
    verify_jwt = true

  [functions.generate-soap-pdf]
    verify_jwt = true
    
  [functions.get-referral-stats]
    verify_jwt = true
    
  [functions.paypal-payment]
    verify_jwt = true
    
  [functions.paypal]
    verify_jwt = true
    
  [functions.send-referral-email]
    verify_jwt = true

  [functions.suggest-procedure-codes]
    verify_jwt = true
    
  [functions.square]
    verify_jwt = true
    
  [functions.stripe-webhook]
    verify_jwt = false
    
  [functions.stripe]
    verify_jwt = true
    
  [functions.transcribe-audio]
    verify_jwt = true
    
  [functions.verify-referral]
    verify_jwt = true
