// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otvgheqffehoykaerckl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90dmdoZXFmZmVob3lrYWVyY2tsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MjQxNDMsImV4cCI6MjA1NDIwMDE0M30.vPwZwD1wMD9sitDMdvg7ruaKYWODvxdee5l9Ktrbook";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);