on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:  # Combined job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        continue-on-error: true  # Continue to the next step even if install fails

      - name: Debug - List files after install (if it runs)
        run: ls -la
        if: always() # Run this step even if the previous step failed

      - name: Build project
        run: npm run build
        continue-on-error: true # Continue so we can check for output even on failure

      - name: Debug - List files in dist after build (if it runs)
        run: |
          echo "Contents of ./dist:"
          ls -la ./dist
        if: always() # Run this even if build fails

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "31.170.166.84"
          username: "u396802645.aidoctornotes.com"
          password: "Wh0said1t#1982"
          local-dir: ./dist/   # Now, this correctly points to the downloaded artifact
          server-dir: "/public_html/"
          delete-removed: true